# Generated by Django 5.1.4 on 2024-12-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('course_id', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=20)),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=5)),
            ],
        ),
    ]
